# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

send_SIGINT <- function(pid) {
    .Call(`_rdaemon_send_SIGINT`, pid)
}

detachConsole <- function() {
    invisible(.Call(`_rdaemon_detachConsole`))
}

getNameMaxLen <- function() {
    .Call(`_rdaemon_getNameMaxLen`)
}

existsGlobalVariable <- function(name) {
    .Call(`_rdaemon_existsGlobalVariable`, name)
}

setGlobalVariable <- function(name, value) {
    invisible(.Call(`_rdaemon_setGlobalVariable`, name, value))
}

getGlobalVariable <- function(name) {
    .Call(`_rdaemon_getGlobalVariable`, name)
}

unsetGlobalVariable <- function(name) {
    invisible(.Call(`_rdaemon_unsetGlobalVariable`, name))
}

isProcessRunning <- function(pid) {
    .Call(`_rdaemon_isProcessRunning`, pid)
}

